= What Does Good UX Content Look Like? 

Good UX writing content at Couchbase needs to adhere to these principles: 

* <<error-free,Good UX Content Has No Errors>>
* <<consistent,Good UX Content is Consistent>>
* <<complete,Good UX Content is Complete>>
* <<inclusive,Good UX Content is Inclusive and Accessible>>
* <<simple,Good UX Content is Simple>>

[#error-free]
== Good UX Content Has No Errors 

We write content that has no typos or grammatical errors. 

We write content that's factually correct, always. 

[#consistent]
== Good UX Content is Consistent 

We use the same word or words to mean the same thing.

We follow industry standards and conventions, but also our own.
(That's why we maintain a xref:styleguide:ROOT:word-list.adoc[word list]). 

We adhere to our xref:voice.adoc[voice and tone standards].

[#complete]
== Good UX Content is Complete 

We explain exactly what the user needs to know. 
We provide all information needed to be successful. 

Users always know where to go, what's next, and what to do. 

We do not sacrifice clarity for the sake of being brief - we take the space to explain what needs to be explained. 

[#inclusive]
== Good UX Content is Inclusive and Accessible 

We write content that's gender neutral and does not exclude or offend any groups of people.
We respect all cultures and gender identities.  

We do not include slang or colloquialisms. 

We create content that anyone can read or use - regardless of any disability. 

We do not write content that others or makes someone feel excluded, othered, or uncomfortable. 

[#simple]
== Good UX Content is Simple

We write content that simplifies the complex. 

We avoid undefined jargon. 

We write to the point, and eliminate fluff or unnecessary words. 

We write content that the user does not have to think about. 