name: Vale npm tests

on:
  pull_request:
    paths: 
      - ValeStyles/**

jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: install asciidoctor
        run: |
          sudo apt-get install -y asciidoctor

      - name: install vale
        run: |
          sudo snap install vale

      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: diagnose Vale
        working-directory: ./ValeStyles
        run: |
          vale -v
          vale ls-dirs
          vale ls-config
          vale ls-vars

      - name: npm test
        working-directory: ./ValeStyles
        run: |
          npm ci
          npm test
